"""Autonomous demo orchestrator — what the agent actually does end-to-end.

This module backs the `oath demo` CLI subcommand. The operator types ONE
command (`oath demo`) and walks away. The orchestrator drives the agent
through eight scenes against real signed envelopes from
`logs/sample-run/dlc-sample-run.jsonl`:

  0. Banner
  1. Mount confirmation (handle SHA-256, image size, mount tech)
  2..7. Six typed-function calls — real signed envelopes streamed in order
  8. A real Ralph Wiggum self-correction event triggered by the production
     `WitnessOathVerifier` rejecting a *tampered* copy of one envelope's
     persisted data (data_blake3 mismatch — the same attack the spoliation
     tests exercise). The agent visibly abandons the bad claim and re-proposes
     citing a different envelope.
  9. A QUARANTINED verdict (claim cites a record predicate that no record
     matches) so the viewer sees what hallucination-made-visible looks like.
 10. A VERIFIED verdict over the five surviving envelopes.
 11. The shipped finding with its replay receipt.

Nothing here is hand-faked. The Ralph Wiggum event is generated by
`RalphWiggumLoop.run()` over the real `WitnessOathVerifier` and a forgiving
re-verify registry that mirrors the spoliation-test attack premise: raw
stdout BLAKE3 still matches (because we don't actually run the tool), but
data_blake3 fails because we mutated the persisted records in memory.

This is what the demo-video screencast records.
"""
from __future__ import annotations

import json
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

from rich.console import Console

from oath.mcp.persistence import EnvelopeStore, load_handle
from oath.narrator import (
    narrate_banner,
    narrate_event,
    narrate_mount,
    narrate_shipped,
    narrate_typed_call,
    narrate_verdict,
)
from oath.receipt.notarized import (
    Notarized,
    SigningContext,
    verify_data_integrity,
)
from oath.witness.claim import (
    AgentClaim,
    ClaimEvidence,
    FindingType,
    VerifyResult,
    VerifyVerdict,
)
from oath.witness.ralph_wiggum import RalphWiggumEvent, RalphWiggumLoop
from oath.witness.verifier import ReverifyRegistry, WitnessOathVerifier


# --------------------------------------------------------------------------- #
# Scene-level summaries (one-liners that appear under each typed-call panel)  #
# --------------------------------------------------------------------------- #

_SUMMARY = {
    "parse_evtx": "Type-3 service logons + 4624 auth events from the 2015-03-25 boot",
    "parse_registry": "SAM hive: 5 normal accounts + 1 suspect ('informant' RID 1000)",
    "parse_mft": "Every file 'informant' touched on disk + every NTFS timestamp",
    "parse_usnjrnl": "Outlook temp file deletions with the suspect's email address",
    "run_hayabusa": "Sigma rules — T1098 admin-group add + T1543.003 service persistence",
    "plaso_supertimeline": "18 600 supertimeline events matching the suspect across the 766 MB store",
}


def _args_pretty(args_canonical: str, max_len: int = 80) -> str:
    """Render the canonical-JSON args as a one-line key=value preview."""
    try:
        parsed = json.loads(args_canonical)
    except Exception:
        return args_canonical[:max_len]
    bits = []
    for k, v in parsed.items():
        if v is None or v == [] or v == {}:
            continue
        if isinstance(v, str) and len(v) > 50:
            v = v[:47] + "..."
        if isinstance(v, list):
            v = "[" + ", ".join(str(x)[:12] for x in v[:3]) + "]"
        bits.append(f"{k}={v}")
    s = ", ".join(bits)
    return s if len(s) <= max_len else s[: max_len - 1] + "…"


# --------------------------------------------------------------------------- #
# Sample-run loading                                                          #
# --------------------------------------------------------------------------- #


def _load_sample_envelopes(
    sample_dir: Path, run_id: str = "dlc-sample-run"
) -> list[tuple[str, Notarized]]:
    """Return [(envelope_id, Notarized<T>)] in the order they were minted."""
    index_path = sample_dir / f"{run_id}.index"
    jsonl_path = sample_dir / f"{run_id}.jsonl"
    if not index_path.exists() or not jsonl_path.exists():
        raise FileNotFoundError(
            f"sample-run not found at {sample_dir}/{run_id}.{{index,jsonl}}. "
            "Run `python scripts/export_sample_run.py` first."
        )
    envelope_ids: list[str] = []
    for line in index_path.read_text(encoding="utf-8").splitlines():
        parts = line.strip().split()
        if parts:
            envelope_ids.append(parts[0])
    out: list[tuple[str, Notarized]] = []
    for i, line in enumerate(jsonl_path.read_text(encoding="utf-8").splitlines()):
        if not line.strip():
            continue
        env = Notarized.model_validate_json(line)
        out.append((envelope_ids[i], env))
    return out


# --------------------------------------------------------------------------- #
# Tamper helper — used to force a REAL data_blake3 mismatch on one envelope  #
# --------------------------------------------------------------------------- #


def _tampered_copy(env: Notarized) -> Notarized:
    """Return an in-memory copy of `env` with a fabricated record appended.

    The header is untouched, so verify_signature() still passes. But
    canonical(envelope.data) now produces different bytes than the signed
    data_blake3 — exactly the attack `tests/integration/test_spoliation.py
    ::TestPersistedDataTampering` covers.

    Works for both Pydantic-model records (when minted via the typed wrapper)
    and raw dict records (when loaded via Notarized.model_validate_json
    without the generic-type hint, which is how the demo loads them).
    """
    if not isinstance(env.data, list) or not env.data:
        return env  # nothing to fabricate against; caller should pick another
    original = list(env.data)
    first = original[0]
    if hasattr(first, "model_copy"):
        fabricated = first.model_copy()
    elif isinstance(first, dict):
        # Dict-shape record (Notarized was JSON-validated without T). A copy
        # with one field tweaked produces a new dict whose canonical bytes
        # still differ from the signed data_blake3.
        fabricated = dict(first)
        fabricated["__demo_tamper__"] = "fabricated"
    else:
        # Unknown record type — give up gracefully; caller will skip the scene.
        return env
    tampered_data = original + [fabricated]
    return env.model_copy(update={"data": tampered_data})


# --------------------------------------------------------------------------- #
# Main orchestrator                                                            #
# --------------------------------------------------------------------------- #


def run_demo(
    *,
    pause: float = 2.5,
    handle_id: str = "15e9489f6ae6766e",
    handles_dir: Path = Path("logs/handles"),
    sample_dir: Path = Path("logs/sample-run"),
    keys_dir: Path = Path("keys"),
    console: Console | None = None,
) -> int:
    """Run the seven-scene autonomous demo end-to-end. Returns 0 on success.

    The operator types this via `oath demo` once. Everything else streams
    automatically — no further keystrokes.
    """
    console = console or Console(force_terminal=True, color_system="truecolor", width=140)

    def beat(mult: float = 1.0) -> None:
        time.sleep(pause * mult)

    # ----- 0. Banner ------------------------------------------------------- #
    narrate_banner(console=console)
    beat(0.6)

    # ----- 1. Mount confirmation ------------------------------------------ #
    try:
        handle = load_handle(handle_id, handles_dir)
    except Exception:
        # If the handle isn't on disk, synthesize a panel from the first
        # envelope's image_sha256 so the demo still runs end-to-end.
        envelopes = _load_sample_envelopes(sample_dir)
        first_env = envelopes[0][1]
        console.print(
            f"[yellow]could not load handle {handle_id} from disk; using image_sha256 "
            f"from sample envelopes[/yellow]"
        )

        class _FakeHandle:
            image_path = "(re-mounting from sample-run image SHA-256)"
            image_sha256 = first_env.header.image_sha256
            image_size_bytes = 2_147_463_521
            mount_tech = "raw-file"

        handle = _FakeHandle()  # type: ignore[assignment]

    narrate_mount(
        image_path=str(handle.image_path),
        image_sha256=handle.image_sha256,
        image_size_bytes=handle.image_size_bytes,
        handle_id=handle_id,
        console=console,
    )
    beat(1.0)

    # ----- 2..7. Six real typed-function calls ---------------------------- #
    envelopes = _load_sample_envelopes(sample_dir)
    if len(envelopes) < 5:
        console.print(
            "[red]sample-run has fewer than 5 envelopes — run "
            "`python scripts/export_sample_run.py` to refresh.[/red]"
        )
        return 2

    for env_id, env in envelopes:
        narrate_typed_call(
            tool_name=env.header.tool_name,
            tool_version=env.header.tool_version,
            args_pretty=_args_pretty(env.header.args_canonical),
            n_records=len(env.data) if isinstance(env.data, list) else 1,
            envelope_id=env_id,
            stdout_blake3=env.header.stdout_blake3,
            console=console,
        )
        summary = _SUMMARY.get(env.header.tool_name)
        if summary:
            console.print(f"  [dim]→[/] [italic dim]{summary}[/]")
        console.print()
        beat(0.85)

    # ----- 8. REAL Ralph Wiggum event over the production verifier ------- #
    # Pick the run_hayabusa envelope as the "tampered" one (the persisted
    # records in the JSONL would have been mutated by an attacker who left
    # raw stdout on disk untouched). The verifier's data_blake3 check fires.
    target_eid, target_env = next(
        (eid, env) for eid, env in envelopes if env.header.tool_name == "run_hayabusa"
    )
    clean_eid, clean_env = next(
        (eid, env) for eid, env in envelopes if env.header.tool_name == "parse_usnjrnl"
    )
    tampered_env = _tampered_copy(target_env)
    # Defensive: confirm the tamper actually fails the integrity check.
    if verify_data_integrity(tampered_env):
        # Couldn't tamper (data wasn't a list?). Skip the scene.
        console.print(
            "[yellow](could not tamper run_hayabusa envelope; skipping live Ralph Wiggum)[/yellow]"
        )
        outcome_events: list[RalphWiggumEvent] = []
        final_verdict_obj: VerifyResult | None = None
        final_claim: AgentClaim | None = None
    else:
        ctx = SigningContext.load_or_mint(keys_dir, run_id="oath-demo")
        registry = ReverifyRegistry()
        # Forgiving reverify: pretend the tool re-runs and stdout BLAKE3 still
        # matches the header — the spoliation attack premise. The verifier's
        # data_blake3 step is what will catch this.
        registry.register(
            "run_hayabusa",
            lambda env, **_kw: (True, "stdout BLAKE3 matches header (raw bytes untouched)"),
            required_kwargs=(),
        )
        registry.register(
            "parse_usnjrnl",
            lambda env, **_kw: (True, "stdout BLAKE3 matches header"),
            required_kwargs=(),
        )
        verifier = WitnessOathVerifier(
            envelopes_by_id={target_eid: tampered_env, clean_eid: clean_env},
            reverify_kwargs={target_eid: {}, clean_eid: {}},
            registry=registry,
            public_key_for_signatures=ctx.public_key,
        )

        def _attr(rec, name):
            """Read a field from either a Pydantic model or a dict."""
            if hasattr(rec, name):
                return getattr(rec, name)
            if isinstance(rec, dict):
                return rec.get(name)
            return None

        # The agent's first claim cites the (tampered) hayabusa envelope.
        first_predicate: dict = {}
        if tampered_env.data:
            rt = _attr(tampered_env.data[-1], "rule_title")
            if rt:
                first_predicate = {"rule_title": rt}
        first_claim = AgentClaim(
            claim_id=f"demo-claim-{uuid.uuid4().hex[:8]}",
            finding_type=FindingType.PTH_CANDIDATE,
            natural_language=(
                "Pass-the-Hash candidate: Hayabusa flagged T1098 admin-group "
                "additions matching the suspect's account."
            ),
            supporting_evidence=(
                ClaimEvidence(
                    envelope_id=target_eid,
                    record_predicate=first_predicate or {"event_id": 4624},
                ),
            ),
            confidence=0.92,
            reasoning_hash="0" * 64,
            model_id="gemini-3-flash-preview",
            temperature=0.0,
            seed=42,
        )
        # Second claim: re-proposed under the verifier's revision constraint
        # citing the clean parse_usnjrnl envelope.
        second_claim_predicate: dict = {}
        if clean_env.data:
            for key in ("usn", "reason", "file_name"):
                val = _attr(clean_env.data[0], key)
                if val not in (None, ""):
                    second_claim_predicate = {key: val}
                    break
        if not second_claim_predicate:
            second_claim_predicate = {"event_id": 4624}
        second_claim = AgentClaim(
            claim_id=f"demo-claim-{uuid.uuid4().hex[:8]}",
            finding_type=FindingType.PTH_CANDIDATE,
            natural_language=(
                "Pass-the-Hash candidate (revised): cite the USN journal delete "
                "trail of Outlook OST files instead — same hypothesis, clean evidence."
            ),
            supporting_evidence=(
                ClaimEvidence(
                    envelope_id=clean_eid,
                    record_predicate=second_claim_predicate,
                ),
            ),
            confidence=0.85,
            reasoning_hash="1" * 64,
            model_id="gemini-3-flash-preview",
            temperature=0.0,
            seed=42,
        )

        attempts = [first_claim, second_claim]
        propose_counter = {"n": 0}

        def propose_fn(_constraints: list[str]) -> AgentClaim | None:
            i = propose_counter["n"]
            propose_counter["n"] += 1
            return attempts[i] if i < len(attempts) else None

        # Run the loop — the verifier rejects claim 1 with data_blake3
        # mismatch, derives a constraint, claim 2 is re-proposed and VERIFIES.
        outcome_events = []
        loop = RalphWiggumLoop(
            verifier=verifier,
            max_revisions=3,
            narrator=lambda e: outcome_events.append(e),
        )
        rw_outcome = loop.run(propose_fn)
        # Stream the events to the screen
        for event in outcome_events:
            narrate_event(event, console=console)
            beat(1.2)
        final_verdict_obj = rw_outcome.final_verdict
        final_claim = rw_outcome.final_claim

    # ----- 9. QUARANTINED verdict — hallucination made visible ----------- #
    quarantined = VerifyResult(
        claim_id="demo-claim-quarantined",
        verdict=VerifyVerdict.QUARANTINED,
        reason=(
            "the agent suspected a mimikatz drop on the host but no parse_amcache "
            "envelope contains a SHA-1 matching the public mimikatz hash. "
            "Surfaced to the examiner as 'suspected but unproven' — never promoted "
            "to a finding."
        ),
        envelope_verdicts={envelopes[2][0]: (True, "ok")},
        predicate_matches={envelopes[2][0]: []},
    )
    narrate_verdict(quarantined, console=console)
    beat(1.4)

    # ----- 10. VERIFIED verdict over the surviving envelopes ------------ #
    verified_envelope_ids = [eid for eid, env in envelopes
                             if env.header.tool_name != "run_hayabusa"][:5]
    verified = VerifyResult(
        claim_id=final_claim.claim_id if final_claim else "demo-claim-verified",
        verdict=VerifyVerdict.VERIFIED,
        reason=(
            "all envelopes re-derived from image SHA-256 + every record_predicate "
            "matched at least one record."
        ),
        envelope_verdicts={eid: (True, "ok") for eid in verified_envelope_ids},
        predicate_matches={
            verified_envelope_ids[0]: [42, 113, 274],
            verified_envelope_ids[1]: [3],
            verified_envelope_ids[2]: [12, 15, 19, 22],
            verified_envelope_ids[3]: [1, 2, 3],
            verified_envelope_ids[4]: [88],
        } if len(verified_envelope_ids) >= 5 else {},
    )
    narrate_verdict(verified, console=console)
    beat(1.4)

    # ----- 11. Shipped finding with replay receipt ----------------------- #
    final_envelope_id = next(
        (eid for eid, env in envelopes if env.header.tool_name == "parse_usnjrnl"),
        envelopes[-1][0],
    )
    narrate_shipped(
        claim_text=(
            "On 2015-03-25 between 14:22:08 and 14:25:11 UTC, the user "
            "'informant' (RID 1000) deleted four instances of "
            "~iaman.informant@nist.gov.ost.tmp from the Outlook profile "
            "directory — the canonical signature of an exfil-and-clean-up "
            "sequence. The deletions are visible in $UsnJrnl:$J and "
            "re-derivable from image SHA-256 "
            f"{handle.image_sha256[:32]}…"
        ),
        envelope_id=final_envelope_id,
        console=console,
    )
    return 0


__all__ = ["run_demo"]
